CREATE TABLE CD (
	  CD_ID			VARCHAR(100)	NOT NULL	COMMENT '코드 아이디'
	, CD_NM			VARCHAR(100)	NOT NULL	COMMENT '코드 명'
	, UP_CD_ID		VARCHAR(100)				COMMENT '상위 코드 아이디'
	, PRIMARY KEY (CD_ID)
);

CREATE TABLE LPP (
	  LPP_ID		NUMBER			NOT NULL	AUTO_INCREMENT	COMMENT '아이디'
	, FILE_PATH		VARCHAR(100)	NOT NULL	COMMENT '파일 경로'
	, EXTR_METHOD	VARCHAR(100)	NOT NULL	COMMENT '추출 방법'
	, DB_TYPE		VARCHAR(100)				COMMENT '데이터베이스 유형'
	, DB_URL		VARCHAR(100)				COMMENT '데이터베이스 주소'
	, DB_PORT		VARCHAR(100)				COMMENT '데이터베이스 포트'
	, DB_NAME		VARCHAR(100)				COMMENT '데이터베이스 명'
	, DB_USER		VARCHAR(100)				COMMENT '데이터베이스 유저'
	, DB_PASS		VARCHAR(100)				COMMENT '데이터베이스 패스워드'
	, TABLE_NAME	VARCHAR(100)				COMMENT '테이블 명'
	, STATUS		VARCHAR(4000)				COMMENT '상태'
	, REG_DATE		DATETIME					COMMENT '등록일'
	, PRIMARY KEY (LPP_ID)
	, FOREIGN KEY (EXTR_METHOD) REFERENCES CD (CD_ID)
	, FOREIGN KEY (STATUS) REFERENCES CD (CD_ID)
);

CREATE TABLE REGEX (
	  REGEX_ID		NUMBER			NOT NULL	AUTO_INCREMENT	COMMENT '아이디'
	, REGEX			VARCHAR(100)	NOT NULL	COMMENT '파일 경로'
	, COLUMN_NAME	VARCHAR(100)	NOT NULL	COMMENT '추출 방법'
	, LPP_ID		NUMBER			NOT NULL	COMMENT '아이디'
	, PRIMARY KEY (REGEX_ID)
	, FOREIGN KEY (LPP_ID) REFERENCES LPP (LPP_ID)
);